name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 13
          platform: x64

      - name: Get Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.10.0

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1.1.0

      - name: Configure
        run: cmake --preset=ci-ubuntu -DGXZN_OS_FS_GENERATE_DOCS=ON --fresh

      - name: Generate documentation
        run: cmake --build --preset=ci-ubuntu --target generate_docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html