name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]


    runs-on: ${{ matrix.os }}

    env:
      preset: ci-$("${{ matrix.os }}".split("-")[0])
      build_directory: build/ci-$("${{ matrix.os }}".split("-")[0])

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      shell: pwsh
      run: cmake "--preset=$preset" --fresh

    - name: Build
      run: cmake --build "$build_directory" --config Release -j 8

    - name: Install
      run: cmake --install "$build_directory" --config Release --prefix prefix

    - name: Test
      working-directory: "$build_directory/code/tests"
      run: ctest --output-on-failure -C Release -j 8
