name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]

    runs-on: ${{ matrix.os }}

    env:
      platform: $(${{ matrix.os }}.split("-")[0])

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        shell: pwsh
        run: cmake "--preset=ci-${{ env.platform }} --fresh

      - name: Build
        run: cmake --build "--preset=${{ env.platform }}-build"

      - name: Install
        run: cmake --install "build/ci-${{ env.platform }}" --config ${{ env.BUILD_TYPE }} --prefix prefix

      - name: Test
        working-directory: $build/ci-${{ env.platform }}/code/tests
        run: ctest "--preset=ci-${{ env.platform }}-test"
