name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        shell: pwsh
        run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])" --fresh

      - name: Build
        run: cmake --build "build/ci-$("${{ matrix.os }}".split("-")[0])" --config ${{ env.BUILD_TYPE }} -j 8

      - name: Install
        run: cmake --install "build/ci-$("${{ matrix.os }}".split("-")[0])" --config ${{ env.BUILD_TYPE }} --prefix prefix

      - name: Test
        working-directory: $build/ci-$("${{ matrix.os }}".split("-")[0])/code/tests
        run: ctest --output-on-failure -C ${{ env.BUILD_TYPE }} -j 8
